services:
  postgres:
    build:
      context: docker/postgres
      dockerfile: Dockerfile
    image: wildfire-postgres:latest
    container_name: wildfire-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wildfire
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/raw
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d wildfire"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
